[package]
name = "monkey-rust"
version = "0.2.3"
authors = ["Jérôme Mahuet <jerome.mahuet@gmail.com>"]

[lib]
name = "monkey_lib"
path = "lib/monkey.rs"

[[bin]]
name = "monkey_repl"
path = "repl/main.rs"

[[bin]]
name = "monkey_exe"
path = "src/main.rs"

[dependencies]
nom = "^3.2"
clap = "~2.27.0"
rustyline = { git = "https://github.com/kkawakam/rustyline" }
